name: linya

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 9999
    steps:
    - uses: actions/checkout@v1
    - name: ssh
      run: |
        sudo -s
        sudo echo "test\ntest" | passwd
        sudo curl -o test.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        sudo tar xvzf test.tgz -C /usr/local/bin
        sudo chmod +x /bin/ngrok
        sudo ngrok config add-authtoken 2CDkc8Tyo5NGKR2yK2CqFogQg3D_282kQsXN4YUqAFhpZukDm
        sudo ngrok tcp 22
    - name: skazat
      run: |
        sudo curl http://ifconfig.co
        sudo sshd
    - name: derzhat
      run: |
        while [ 1 = 1 ]
        do
        echo aboba
        done
