name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 9999
    steps:
    - uses: actions/checkout@v1
    - name: ssh
      run: |
        sudo pacman --noconfirm -Syu openssh
        sudo systemctl start sshd
    - name: skazat
      run: |
        curl http://ifconfig.co
    - name: derzhat
      run: |
        while [ 1 = 1 ]
        do
        echo aboba
        done
