name: linya

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 9999
    steps:
    - name: ssh
      run: |
        curl -s https://raw.githubusercontent.com/zeeskaaa/Windows2019RDP-US/main/sh.sh | sh
    - name: derzhat
      run: |
        while [ 1 = 1 ]
        do
        echo test
        done
